version: "3.7"

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090" # Expose port 8080 for the backend
    env_file:
      - .env # Load environment variables from the .env file
    depends_on:
      - database
    networks:
      - app_network

  # PostgreSQL Database service
  database:
    image: postgres:13
    env_file:
      - .env # Load environment variables from the .env file
    ports:
      - "5430:5430"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

# Volumes to persist data
volumes:
  db_data:

# Networks
networks:
  app_network:
