version: "3.8"

services:
  backend:
    build: .
    ports: ["8090:8090"]
    env_file: .env
    depends_on:
      - database
    networks: ["app_network"]

  database:
    image: postgres:13
    env_file: .env
    ports: ["5430:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
    networks: ["app_network"]
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # Allow passwordless connections

volumes:
  db_data:

networks:
  app_network:
